### ISSUE TITLE
"compressible::turbulentTemperatureCoupledBaffleMixed" boundary condition not included in the solver

### ISSUE THREAD

**Issue by gunjansauti** [fmuni/boilingFoam-PUBLIC#3]
I have tried running the case "flowBoilingCHT_AR1_water_q100k" with OpenFoam v2306. However, I am not able to run the code, with an error "Unknown patchField type compressible::turbulentTemperatureCoupledBaffleMixed for patch type mappedWall."
I

**Comment by fmuni** [comment]
As mentioned in the [README.md](https://github.com/fmuni/boilingFoam-PUBLIC/blob/master/README.md?plain=1#L2), boilingFoam works with OpenFOAM-v2106. We haven't tested it for other versions and we are not currently planning to.

**Comment by fmuni** [comment]
Actually, you raised a good point. 

I would recommend using __OpenFOAM-v2006__ for boilingFoam. All versions of the ESI OpenFOAM after that rank at the top of my list of most bugged software I ever had the displeasure of working with. I change the README.md accordingly.

**Comment by gunjansauti** [comment]
Oh sorry, I forgot that I put up a question here. The /src/thermoTools/ directory was not sourced in the icoBoilingFoam solver. After sourcing it, the solver works fine. Although I have another query. The code is able to run for Stefan case (1D), and the flow boiling case (3D). But when I try to run it for a 2D case I built (with only 1 mesh element in Z-direction), the mass source term remains (mDot) zero all the time, however, mDot0 is nonzero. Laplacian smoothing somehow creates this problem. Did you face any similar problem?

**Comment by fmuni** [comment]
Yes, if you want to compile and run with OpenFOAM-2312 you must add -lthermoTools in Make/options and change mesh.data:: into mesh.data() in icoBoilingFoam.

The Laplacian smoothing should not reduce mDot to zero in 2D, I have never seen that happening. The empty boundary conditions on the dummy direction preclude any diffusive flux. Check that your diffusion coefficient makes sense for your mesh.

**Comment by gunjansauti** [comment]
That's a good point! Thanks, I am definitely messing up the diffusion coefficient.
