### ISSUE TITLE
Several errors and warnings when trying to compile OpenFOAM v2006

### ISSUE THREAD

**Issue by MontelukastNa** [fmuni/boilingFoam-PUBLIC#5]
Hello, fmuni 

I am currently trying to compile it with OpenFOAM v2006, but I have encountered several errors and warnings during the process. Here are the details of the issues I am facing:

In file included from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/instantList.H:37:0,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/fileOperation.H:48,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/IOobjectTemplates.C:30,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/IOobject.H:589,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/regIOobject.H:44,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/objectRegistry.H:44,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/polyMesh.H:47,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvMesh.H:53,
                 from cellCuts/cutCell/cutCell.H:47,
                 from cellCuts/cutCell/cutCell.C:31:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/instant.H:67:30: error: ‘Foam::Instant<Foam::word>::Instant’ names constructor
In file included from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/List.C:31:0,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/List.H:386,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/HashTable.C:33,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/HashTable.H:925,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/objectRegistry.H:42,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/polyMesh.H:47,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvMesh.H:53,
                 from cellCuts/cutCell/cutCell.H:47,
                 from cellCuts/cutCell/cutCell.C:31:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H: In instantiation of ‘class Foam::FixedList<int, 2u>’:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/Pair.H:66:7:   required from ‘class Foam::Pair<int>’
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/ListOpsTemplates.C:873:1:   required from here
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H:79:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
In file included from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/objectRegistry.H:45:0,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/polyMesh.H:47,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvMesh.H:53,
                 from cellCuts/cutCell/cutCell.H:47,
                 from cellCuts/cutCell/cutCell.C:31:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/wordRes.H:114:29: error: ‘Foam::List<Foam::wordRe>::List’ names constructor
In file included from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/List.C:31:0,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/List.H:386,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/HashTable.C:33,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/HashTable.H:925,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/objectRegistry.H:42,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/polyMesh.H:47,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvMesh.H:53,
                 from cellCuts/cutCell/cutCell.H:47,
                 from cellCuts/cutCell/cutCell.C:31:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H: In instantiation of ‘class Foam::FixedList<double, 2u>’:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/Pair.H:66:7:   required from ‘class Foam::Pair<double>’
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/MinMaxOps.H:162:39:   required from here
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H:79:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H: In instantiation of ‘class Foam::FixedList<bool, 1u>’:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/SolverPerformance.H:94:53:   required from ‘class Foam::SolverPerformance<double>’
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/solverPerformance.H:50:56:   required from here
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H:79:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H: In instantiation of ‘class Foam::FixedList<double, 7u>’:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/dimensionSet.H:103:19:   required from here
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FixedList.H:79:1: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
In file included from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/Time.H:47:0,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/dataTemplates.C:29,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/data.H:116,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvMesh.H:60,
                 from cellCuts/cutCell/cutCell.H:47,
                 from cellCuts/cutCell/cutCell.C:31:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FIFOStack.H: In instantiation of ‘class Foam::FIFOStack<Foam::word>’:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/Time.H:164:33:   required from here
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/FIFOStack.H:61:26: error: no members matching ‘Foam::SLList<Foam::word> {aka Foam::LList<Foam::SLListBase, Foam::word>}::SLList’ in ‘Foam::SLList<Foam::word> {aka class Foam::LList<Foam::SLListBase, Foam::word>}’
In file included from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/edgeHashes.H:39:0,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/transformList.H:44,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/mapDistribute.H:140,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/globalMeshDataTemplates.C:31,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/globalMeshData.H:628,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/GeometricBoundaryField.C:31,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/GeometricField.C:1375,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/GeometricField.H:792,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/GeometricScalarField.H:40,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/GeometricFields.H:40,
                 from /home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/volFields.H:39,
                 from cellCuts/cutCell/cutCell.H:48,
                 from cellCuts/cutCell/cutCell.C:31:
/home/dyfluid/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/EdgeMap.H:59:43: error: ‘Foam::HashTable<T, Foam::edge, Foam::Hash<Foam::edge> >::HashTable’ names constructor
make: *** [/home/dyfluid/OpenFOAM/OpenFOAM-v2006/wmake/rules/General/transform:35：/home/dyfluid/OpenFOAM/OpenFOAM-v2006/build/linux64GccDPInt32Opt/boilingFoam-PUBLIC/src/geometricVoF/cellCuts/cutCell/cutCell.o] error 1

I would greatly appreciate any guidance or suggestions on how to resolve these errors. Thank you in advance for your help!

Best regards,
Na

**Comment by fmuni** [comment]
Hello,

boilingFoam does not compile with FO2006. Please, follow the README.md file for info regarding the supported OF versions and how to install them.
