### ISSUE TITLE
Buoyancy Effect Missing and Pressure Variations in Condensing Bubble Simulation with icoBoilingFoam Solver

### ISSUE THREAD

**Issue by zakariya-2000** [fmuni/boilingFoam-PUBLIC#6]
I am simulating a 2D condensing bubble using the icoBoilingFoam solver, where the gravitational acceleration is set to -9.81 m/s² in the y direction. The bubble is initialized using setFields with alpha.liquid = 0 inside the bubble and the saturation temperature. The temperature outside the bubble is below saturation, with a temperature difference between 1-10 K.

Despite the expected buoyancy, the bubble remains stationary and condenses at its initial position. The density difference inside and outside the bubble is clearly visible, and pressure variations due to gravity are present. However, I am observing unexpected variations in p_rgh due to gravity, which I haven't encountered in similar cases using the interFoam solver.

I have also adjusted the smoothing coefficient to the square of the mesh size but still cannot achieve the expected rising behavior of the bubble due to buoyancy.

Could you provide guidance on resolving this issue, so the buoyancy effect becomes visible and the bubble rises while condensing?

**Comment by fmuni** [comment]
Can you be more precise regarding the simulation you are trying to run and the problems you encountered? We haven’t experienced such issues when activating gravity.

**Comment by zakariya-2000** [comment]
Dear Sir/Madam,

Thank you for your prompt response. I appreciate your attention to the
issue.

To provide more clarity, I have attached my job directory for your
reference. It contains all the case files used in the simulation.
Additionally, I have included a short video showing the behavior of the
condensing bubble, where it remains stationary instead of rising due to
buoyancy.

Could you kindly review the setup and help identify any potential issues?

I look forward to your insights and assistance.

Best regards,

Ahmed Zakariya Hamza

M.Tech,IIT Kharagpur

**Comment by fmuni** [comment]
I can’t find the attachment. Can you please reply directly on GitHub and attach the file to your comment?

**Comment by zakariya-2000** [comment]
Thank you for your response.

I have attached my job directory for the simulation, along with a video demonstrating the issue where the condensing bubble does not rise due to buoyancy. Could you please take a look and help identify the problem?

I appreciate your time and assistance.
[vapourbubble_condensing_sample.zip](https://github.com/user-attachments/files/17365897/vapourbubble_condensing_sample.zip)

**Comment by zakariya-2000** [comment]
I’ve found the issue. It turns out that the bubble was condensing much faster than expected due to a large Jakob number, causing it to condense within a few microseconds, preventing the observation of any bubble rise. The problem was resolved after using a smaller Jakob number.

Thank you for your support, and I apologize for any confusion caused earlier.

**Comment by fmuni** [comment]
Great, thanks for looking into this. I can close the issue then.
